repos:
  - repo: local
    hooks:
      - id: flutter-import-sorter
        name: flutter-import-sorter
        entry: flutter pub run import_sorter:main
        language: system
      - id: dart-format
        name: dart-format
        entry: dart format .
        language: system
        pass_filenames: false
      - id: flutter-analyze
        name: flutter-analyze
        entry: flutter analyze
        language: system
        pass_filenames: false