include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_multiple_declarations_per_line: true
    lines_longer_than_80_chars: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    always_declare_return_types: true
    always_use_package_imports: true
    type_annotate_public_apis: true
    avoid_web_libraries_in_flutter: false
    use_build_context_synchronously: false
    prefer_interpolation_to_compose_strings: false
    sort_pub_dependencies: false
    require_trailing_commas: true
    use_super_parameters: true